version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Maila210526@
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: employee-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Maila210526@
      DB_NAME: employee_management
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: employee-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
