apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: employee-management
spec:
  type: ClusterIP
  selector:
    app: employee-frontend
  ports:
  - port: 80
    targetPort: 80
